apk:
  - exiftool # Metadata editor

  # --- DEPEND #1 qrcode[pil] (from Pillow) ---
  - libjpeg
  - zlib
  # --- END_DEPEND #1 ---

  - python3  
pip:
  - qrcode[pil]        # QR Code generator
  - CurrencyConverter  # Currency converter
  - "--no-binary :all:"  # Forces all packages to build from source

# Build-only dependencies
# These will be installed, used for setup/pip, and removed before final export.
apk_build:
  - build-base       # GCC, Make, libc-dev
  - linux-headers
  - python3-dev      # Python developer tools
  - py3-setuptools   
  - py3-pip          # Pip for python
  - git              # Sometimes needed for pip install git+...
  # --- DEPEND #1 qrcode[pil] (from Pillow) ---
  - jpeg-dev 
  - zlib-dev
  # --- END_DEPEND #1 ---
  
